owner: tiste
repo: status

sites:
  - name: 1 à 10
    url: https://1a10.app
  - name: 1 à 10 API
    url: https://api.1a10.app/api/health
  - name: cronping
    url: https://cronping.tiste.io
  - name: Engraver
    url: https://engraver.tiste.io
  - name: Hey Be See
    url: https://heybesee.fr
  - name: Setlist
    url: https://setlist.live
  - name: Setlist app
    url: https://app.setlist.live
  - name: Setlist API
    url: https://api.setlist.live/health
  - name: Swunitch
    url: https://convertisseur-temps-course.tiste.io
  - name: Swunitch API
    url: https://swunitch-api.tiste.io/races
  - name: Yahtzee app
    url: https://yahtzee.game
  - name: Yahtzee API
    url: https://api.yahtzee.game
  - name: www
    url: https://tiste.io

status-website:
  cname: status.tiste.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page gather all services I work on, from personal projects to open-source ones.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
